version: "3.9"

services:
  app:
    build:
      context: ./server
    container_name: showroom-creator
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    working_dir: /app
    environment:
      - NODE_ENV=development
      - DB_URI=mongodb://mongo:27017/showroom
    depends_on:
      - mongo
    networks:
      - showroom-network

  mongo:
    container_name: showroom-mongo
    image: mongo:latest
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - ./mongo:/data/db
    networks:
      - showroom-network
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=3^9r4$f$o7k*TSk9rJBWbh
      - MONGO_INITDB_DATABASE=showroom

networks:
  showroom-network:
    driver: bridge